import Head from 'next/head'
import { CarForm } from '../lib/CarForm'
import { SearchForm } from '../lib/SearchForm'

export default function Home() {
  return (
    <div>
      <Head>
        <title>First Redis App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Create a car</h1>
      <CarForm />
      <SearchForm />
    </div>
  )
}
